import { MetadataRoute } from 'next'
import { env } from './lib/env';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = env.NEXT_PUBLIC_SITE_URL;
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/_next/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/about',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/about',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/about',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
