import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  // CRITICAL: Always use non-www to match site redirects and prevent SEO issues
  const baseUrl = 'https://cowboykimono.com';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/about/',
          '/custom-kimonos/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/_next/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/about/',
          '/custom-kimonos/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/blog/',
          '/shop/',
          '/downloads/',
          '/about/',
          '/custom-kimonos/',
          '/images/',
          '/sitemap.xml',
        ],
        disallow: [
          '/private/',
          '/admin/',
          '/wp-content/',
          '/wp-admin/',
          '/wp-includes/',
          '/api/',
          '/debug/',
          '/shop-1',
          '/kimono-builder',
          '/contact-2',
          '/search',
          '/error',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
